name: CI

on:
  push:
    branches:
      - '**'
env:
  CONTENT_PLUGIN_RELEASE-TAG: 'release-8.0.0' # Set this to the desired release tag of the content plugin

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      version_number: ${{ github.ref_name }}
      build_number: ${{ github.run_number }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js 10
        uses: actions/setup-node@v3
        with:
          node-version: 10.24.1

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package.json') }}

      - name: Clone plugins (from fork)
        run: |
          git clone --branch ${{ env.CONTENT_PLUGIN_RELEASE-TAG }} https://github.com/vinodbhorge/sunbird-content-plugins.git plugins

      - name: Install dependencies
        run: |
          which bower || sudo npm install -g bower@1.8.0
          which grunt || sudo npm install -g grunt-cli@1.2.0
          which gulp || sudo npm install -g gulp@3.9.1
          sudo apt-get install build-essential libpng-dev

      - name: Bower cache clean
        run: cd app && bower cache clean --allow-root

      - name: Bower install
        run: cd app && bower install --force --allow-root

      - name: Install global npm packages
        run: npm install --save-dev eslint-config-standard eslint-plugin-import eslint-plugin-node eslint-plugin-promise --legacy-peer-deps

      - name: Gulp packageCorePlugins
        run: gulp packageCorePlugins

      - name: Plugin build
        run: npm run plugin-build

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test
        continue-on-error: true

      - name: Copy coverage
        run: |
          mkdir -p /tmp/coverage
          cp ./coverage/lcov/PhantomJS*/lcov.info /tmp/coverage || true

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: /tmp/coverage

      - name: Run Lint
        run: npm run lint

      - name: Set up Node.js 14 (for Sonar)
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install SonarQube scanner
        run: npm install -g sonarqube-scanner

      - name: Run SonarQube scanner
        working-directory: content-editor
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: sonar-scanner